service: google-gae-oauth-drive-example # see https://cloud.google.com/appengine/docs/go/
runtime: go                             # see https://cloud.google.com/appengine/docs/go/
api_version: go1.8                      # used when appengine supports different go versions

# These are specified by using command line flag
# application: my-application-id  # defined when you create your app using google dev console
# version: alpha                  # you can run multiple versions of an app and A/B test

handlers:
- url: /fulfillments
  script: _go_app

- url: /.*
  script: _go_app
  login: required

nobuild_files:
- vendor/

skip_files:
- vendor/

includes:
- env.yaml
